import type { Category, HotSearch, Resource } from "./types";

/**
 * Phase 1 临时数据源（无数据库可跑）。
 * 结构完全对齐 resources / categories / tags / resource_links 四张表，
 * 接入 Prisma 后用同样的查询函数替换即可，组件层无需改动。
 */

export const CATEGORIES: Category[] = [
  {
    id: 1,
    name: "影视",
    slug: "film",
    parentId: null,
    icon: "🎬",
    sortOrder: 1,
    children: [
      { name: "电影", slug: "film" },
      { name: "电视剧", slug: "tv" },
      { name: "纪录片", slug: "documentary" },
      { name: "动漫", slug: "anime" },
      { name: "4K·蓝光", slug: "4k" },
    ],
  },
  {
    id: 2,
    name: "软件",
    slug: "software",
    parentId: null,
    icon: "💿",
    sortOrder: 2,
    children: [
      { name: "Windows", slug: "windows" },
      { name: "macOS", slug: "macos" },
      { name: "Android", slug: "android" },
      { name: "开发", slug: "dev" },
      { name: "设计", slug: "design" },
    ],
  },
  {
    id: 3,
    name: "办公",
    slug: "office",
    parentId: null,
    icon: "📄",
    sortOrder: 3,
    children: [
      { name: "PPT 模板", slug: "ppt" },
      { name: "Excel", slug: "excel" },
      { name: "Word", slug: "word" },
      { name: "字体", slug: "font" },
      { name: "PDF", slug: "pdf" },
    ],
  },
  {
    id: 4,
    name: "学习",
    slug: "course",
    parentId: null,
    icon: "🎓",
    sortOrder: 4,
    children: [
      { name: "编程", slug: "coding" },
      { name: "AI 课程", slug: "ai-course" },
      { name: "外语", slug: "language" },
      { name: "考研", slug: "kaoyan" },
      { name: "职业技能", slug: "skill" },
    ],
  },
  {
    id: 5,
    name: "电子书",
    slug: "ebook",
    parentId: null,
    icon: "📚",
    sortOrder: 5,
    children: [
      { name: "小说", slug: "novel" },
      { name: "计算机", slug: "cs" },
      { name: "人文社科", slug: "humanity" },
      { name: "有声书", slug: "audiobook" },
    ],
  },
  {
    id: 6,
    name: "素材",
    slug: "material",
    parentId: null,
    icon: "🎨",
    sortOrder: 6,
    children: [
      { name: "图片", slug: "image" },
      { name: "视频", slug: "video" },
      { name: "音乐", slug: "music" },
      { name: "PSD", slug: "psd" },
    ],
  },
  {
    id: 7,
    name: "AI",
    slug: "ai",
    parentId: null,
    icon: "🤖",
    sortOrder: 7,
    children: [
      { name: "AI 软件", slug: "ai-app" },
      { name: "AI 教程", slug: "ai-tutorial" },
      { name: "Prompt", slug: "prompt" },
      { name: "模型", slug: "model" },
    ],
  },
  {
    id: 8,
    name: "工具",
    slug: "tool",
    parentId: null,
    icon: "🧰",
    sortOrder: 8,
    children: [
      { name: "在线工具", slug: "online" },
      { name: "开源项目", slug: "opensource" },
      { name: "网站导航", slug: "navi" },
    ],
  },
];

const r = (
  id: number,
  title: string,
  slug: string,
  categorySlug: string,
  extra: Partial<Resource>,
): Resource => ({
  id,
  title,
  slug,
  categorySlug,
  status: "published",
  views: 0,
  likes: 0,
  createdAt: "2026-09-01",
  updatedAt: "2026-09-20",
  tags: [],
  links: [],
  ...extra,
});

export const RESOURCES: Resource[] = [
  r(101, "黑镜 第七季 Black Mirror S07", "black-mirror-s07", "film", {
    description:
      "《黑镜》第七季回归，六集独立单元剧，延续科技反乌托邦叙事，1080P 中英双语字幕，含官方预告与幕后花絮。",
    year: 2026,
    region: "英国",
    language: "英语 / 简体中文",
    quality: "1080P",
    size: "18.6 GB",
    views: 48213,
    likes: 1260,
    tags: ["科幻", "剧情", "Netflix", "1080P", "中文字幕"],
    createdAt: "2026-09-24",
    links: [
      { id: 1, resourceId: 101, panType: "quark", url: "https://pan.quark.cn/s/demo001", status: "active" },
      { id: 2, resourceId: 101, panType: "baidu", url: "https://pan.baidu.com/s/demo002", password: "bm07", status: "unknown" },
    ],
  }),
  r(102, "Microsoft Office 2024 专业增强版", "office-2024-pro-plus", "software", {
    description: "Office 2024 专业增强版离线安装包，含 Word / Excel / PowerPoint / Outlook / Access，支持 Windows 10/11，附 KMS 激活说明。",
    version: "2024",
    size: "4.2 GB",
    language: "简体中文",
    views: 92831,
    likes: 3380,
    tags: ["Office", "Windows", "办公", "安装包"],
    createdAt: "2026-09-23",
    links: [
      { id: 3, resourceId: 102, panType: "quark", url: "https://pan.quark.cn/s/demo003", status: "active" },
      { id: 4, resourceId: 102, panType: "baidu", url: "https://pan.baidu.com/s/demo004", password: "of24", status: "active" },
    ],
  }),
  r(103, "Adobe Photoshop 2025 (v26.x) for macOS", "photoshop-2025-macos", "software", {
    description: "Adobe Photoshop 2025 macOS 原版镜像 + 安装教程，支持 Apple Silicon 原生运行，含 Neural Filters 离线组件。",
    version: "2025 v26.4",
    size: "3.8 GB",
    language: "简体中文 / 英文",
    views: 61204,
    likes: 2110,
    tags: ["Photoshop", "macOS", "设计", "Adobe"],
    createdAt: "2026-09-22",
    links: [{ id: 5, resourceId: 103, panType: "quark", url: "https://pan.quark.cn/s/demo005", status: "active" }],
  }),
  r(104, "2026 商务汇报 PPT 模板合集（1200 套）", "business-ppt-templates-2026", "office", {
    description: "1200 套高端商务汇报 PPT 模板，含年终总结、融资路演、产品发布、数据看板，附字体与图表素材，PPTX 源文件可编辑。",
    size: "9.7 GB",
    views: 158209,
    likes: 5620,
    tags: ["PPT", "模板", "年终总结", "路演"],
    createdAt: "2026-09-21",
    links: [
      { id: 6, resourceId: 104, panType: "quark", url: "https://pan.quark.cn/s/demo006", status: "active" },
      { id: 7, resourceId: 104, panType: "baidu", url: "https://pan.baidu.com/s/demo007", password: "ppt9", status: "unknown" },
    ],
  }),
  r(105, "Python 全栈开发从入门到实战（2026 版）", "python-full-stack-2026", "course", {
    description: "零基础到全栈：Python 语法、Django / FastAPI、爬虫、数据分析、Docker 部署，共 42 小时视频 + 配套代码与课件。",
    year: 2026,
    size: "52.3 GB",
    language: "中文讲解",
    author: "星球整理",
    views: 74318,
    likes: 2870,
    tags: ["Python", "编程", "全栈", "视频课程"],
    createdAt: "2026-09-20",
    links: [{ id: 8, resourceId: 105, panType: "quark", url: "https://pan.quark.cn/s/demo008", status: "active" }],
  }),
  r(106, "三体全集 有声书（刘慈欣）", "three-body-audiobook", "ebook", {
    description: "《三体》三部曲全文有声演播，专业主播多人配音，MP3 高码率，附 TXT + EPUB 电子版，通勤连载首选。",
    author: "刘慈欣",
    size: "2.1 GB",
    language: "简体中文",
    views: 33507,
    likes: 1420,
    tags: ["科幻", "有声书", "小说", "文学"],
    createdAt: "2026-09-19",
    links: [{ id: 9, resourceId: 106, panType: "baidu", url: "https://pan.baidu.com/s/demo009", password: "san1", status: "active" }],
  }),
  r(107, "ChatGPT / Claude 高阶 Prompt 手册", "ai-prompt-handbook", "ai", {
    description: "收录 800+ 结构化 Prompt 模板：写作、编程、数据分析、绘画 Midjourney、Agent 编排，含中英对照与可直接复制的 Markdown 源文件。",
    size: "268 MB",
    views: 88421,
    likes: 4130,
    tags: ["Prompt", "ChatGPT", "AI", "效率"],
    createdAt: "2026-09-18",
    links: [
      { id: 10, resourceId: 107, panType: "quark", url: "https://pan.quark.cn/s/demo010", status: "active" },
      { id: 11, resourceId: 107, panType: "baidu", url: "https://pan.baidu.com/s/demo011", status: "expired" },
    ],
  }),
  r(108, "蓝色星球 II 4K HDR 纪录片", "blue-planet-ii-4k", "film", {
    description: "BBC 纪录片《蓝色星球 II》4K HDR 原盘，7 集合集，杜比视界，内封简体中字，附幕后花絮与原声带。",
    year: 2017,
    quality: "4K HDR",
    size: "96.4 GB",
    views: 41268,
    likes: 1890,
    tags: ["纪录片", "BBC", "自然", "4K"],
    createdAt: "2026-09-17",
    links: [{ id: 12, resourceId: 108, panType: "quark", url: "https://pan.quark.cn/s/demo012", status: "active" }],
  }),
  r(109, "Windows 11 25H2 官方原版镜像合集", "windows-11-25h2-iso", "software", {
    description: "Windows 11 25H2 官方 MSDN 原版镜像，含家庭版 / 专业版 / 企业版 LTSC，x64 + ARM64，SHA1 校验值齐全。",
    version: "25H2",
    size: "12.8 GB",
    views: 121340,
    likes: 4720,
    tags: ["Windows", "系统镜像", "MSDN", "原版"],
    createdAt: "2026-09-16",
    links: [
      { id: 13, resourceId: 109, panType: "quark", url: "https://pan.quark.cn/s/demo013", status: "active" },
      { id: 14, resourceId: 109, panType: "baidu", url: "https://pan.baidu.com/s/demo014", password: "w11x", status: "active" },
    ],
  }),
  r(110, "Excel 函数与数据可视化进阶教程", "excel-advanced-tutorial", "office", {
    description: "从 VLOOKUP 到 Power Query、Power Pivot、动态数组，配套 80 个真实业务案例源文件，财务与运营岗适用。",
    size: "6.4 GB",
    views: 28906,
    likes: 980,
    tags: ["Excel", "数据分析", "教程", "模板"],
    createdAt: "2026-09-15",
    links: [{ id: 15, resourceId: 110, panType: "quark", url: "https://pan.quark.cn/s/demo015", status: "active" }],
  }),
  r(111, "进击的巨人 全四季 蓝光收藏版", "attack-on-titan-complete", "film", {
    description: "《进击的巨人》全四季 + OAD + 最终季完结篇，1080P 蓝光压制，简日双语字幕，含剧场版与官方画册。",
    year: 2023,
    region: "日本",
    quality: "1080P 蓝光",
    size: "78.2 GB",
    views: 56120,
    likes: 2430,
    tags: ["动漫", "日番", "热血", "中文字幕"],
    createdAt: "2026-09-14",
    links: [{ id: 16, resourceId: 111, panType: "quark", url: "https://pan.quark.cn/s/demo016", status: "active" }],
  }),
  r(112, "UI 设计素材库：图标 / Mockup / PSD 源文件", "ui-design-assets-pack", "material", {
    description: "120 GB 级设计素材精选包：5000+ 矢量图标、300+ 场景 Mockup、600+ PSD 分层源文件，含商用字体授权说明。",
    size: "63.5 GB",
    views: 37455,
    likes: 1670,
    tags: ["PSD", "UI", "图标", "设计素材"],
    createdAt: "2026-09-13",
    links: [
      { id: 17, resourceId: 112, panType: "quark", url: "https://pan.quark.cn/s/demo017", status: "active" },
      { id: 18, resourceId: 112, panType: "baidu", url: "https://pan.baidu.com/s/demo018", password: "ui23", status: "unknown" },
    ],
  }),
  r(113, "考研英语一 全程班（词汇 · 真题 · 作文）", "kaoyan-english-full-course", "course", {
    description: "2027 考研英语一全程班，含 5500 词串讲、近 20 年真题精析、大小作文模板，配套 PDF 讲义与背诵计划表。",
    year: 2026,
    size: "28.9 GB",
    views: 21987,
    likes: 760,
    tags: ["考研", "英语", "真题", "网课"],
    createdAt: "2026-09-12",
    links: [{ id: 19, resourceId: 113, panType: "baidu", url: "https://pan.baidu.com/s/demo019", password: "ky26", status: "active" }],
  }),
  r(114, "高效开源神器合集（Windows / macOS）", "open-source-tools-pack", "tool", {
    description: "30 款效率开源工具打包：Everything、uTools 替代、Snipaste、LocalSend、Draw.io 离线版、HandBrake 等，全部免安装绿色版。",
    size: "1.9 GB",
    views: 45602,
    likes: 2050,
    tags: ["开源", "效率工具", "绿色版", "合集"],
    createdAt: "2026-09-11",
    links: [{ id: 20, resourceId: 114, panType: "quark", url: "https://pan.quark.cn/s/demo020", status: "active" }],
  }),
  r(115, "Adobe Premiere Pro 2025 剪辑实战课", "premiere-pro-2025-course", "course", {
    description: "18 小时 PR 剪辑系统课：调色、转场、字幕 Batch、音画同步、短视频流程，含 200 GB 练习素材与工程文件。",
    year: 2026,
    size: "215 GB",
    views: 30418,
    likes: 1130,
    tags: ["Premiere", "剪辑", "视频", "教程"],
    createdAt: "2026-09-10",
    links: [{ id: 21, resourceId: 115, panType: "quark", url: "https://pan.quark.cn/s/demo021", status: "active" }],
  }),
  r(116, "计算机科学丛书 100 本（影印版 PDF）", "cs-books-100-pdf", "ebook", {
    description: "涵盖算法、操作系统、计算机网络、编译原理、分布式系统、ML 的经典书单，高清影印 PDF，附思维导图与读书笔记。",
    size: "11.2 GB",
    views: 67210,
    likes: 3210,
    tags: ["计算机", "PDF", "技术书", "书单"],
    createdAt: "2026-09-09",
    links: [
      { id: 22, resourceId: 116, panType: "quark", url: "https://pan.quark.cn/s/demo022", status: "active" },
      { id: 23, resourceId: 116, panType: "baidu", url: "https://pan.baidu.com/s/demo023", status: "unknown" },
    ],
  }),
  r(117, "思源宋体 + 站酷系列商用字体包", "commercial-fonts-pack", "office", {
    description: "整理 120 款可商用字体：思源宋体 / 黑体、站酷高端黑、阿里巴巴普惠体、OPPO Sans，附商用授权说明与安装教程。",
    size: "3.4 GB",
    views: 52874,
    likes: 2480,
    tags: ["字体", "商用", "设计", "素材"],
    createdAt: "2026-09-08",
    links: [{ id: 24, resourceId: 117, panType: "quark", url: "https://pan.quark.cn/s/demo024", status: "active" }],
  }),
  r(118, "2026 无版权背景音乐库（BGM 3000 首）", "royalty-free-bgm-2026", "material", {
    description: "3000 首可商用无版权背景音乐，按情绪 / 场景分类，WAV + MP3 双格式，Vlog、短视频、播客配乐即取即用。",
    size: "26.7 GB",
    views: 24156,
    likes: 890,
    tags: ["BGM", "音乐", "无版权", "商用"],
    createdAt: "2026-09-07",
    links: [{ id: 25, resourceId: 118, panType: "baidu", url: "https://pan.baidu.com/s/demo025", password: "bgm1", status: "active" }],
  }),
  r(119, "本地大模型部署指南 + Llama / Qwen 量化权重", "local-llm-deploy-kit", "ai", {
    description: "手把手在消费级显卡跑本地大模型：Ollama / vLLM / LM Studio，含 Qwen3、Llama 4 的 GGUF 量化下载清单与评测数据。",
    size: "512 MB",
    views: 39980,
    likes: 1740,
    tags: ["大模型", "本地部署", "Qwen", "AI"],
    createdAt: "2026-09-06",
    links: [{ id: 26, resourceId: 119, panType: "quark", url: "https://pan.quark.cn/s/demo026", status: "active" }],
  }),
  r(120, "iPhone / Android 精品 App 历史版本合集", "mobile-app-archive", "software", {
    description: "常用 App 历史版本归档：微信、抖音、Notion、Obsidian、网易云音乐等，含 IPA 安装包与 APK 历史版本，支持降级安装。",
    size: "18.3 GB",
    views: 18324,
    likes: 620,
    tags: ["Android", "iOS", "历史版本", "降级"],
    createdAt: "2026-09-05",
    links: [{ id: 27, resourceId: 120, panType: "quark", url: "https://pan.quark.cn/s/demo027", status: "active" }],
  }),
];

export const HOT_SEARCHES: HotSearch[] = [
  { keyword: "Office 2024", count: 12840, trend: "up" },
  { keyword: "黑镜 第七季", count: 9620, trend: "up" },
  { keyword: "PPT 模板", count: 8915, trend: "flat" },
  { keyword: "Windows 11", count: 7630, trend: "up" },
  { keyword: "Photoshop", count: 6428, trend: "flat" },
  { keyword: "Python 教程", count: 5810, trend: "up" },
  { keyword: "三体", count: 4206, trend: "down" },
  { keyword: "Node Exporter", count: 3120, trend: "flat" },
  { keyword: "考研英语", count: 2780, trend: "up" },
  { keyword: "商用字体", count: 2140, trend: "flat" },
];
